version:  '3.7'

services:
  database:
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    ports:
      - 33060:3306
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - symfony
  
  php:
    container_name: client-server-php
    volumes:
      - './server/:/usr/src/server'
      - './client/:/usr/src/client'
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    depends_on:
      - database
    env_file:
      - .env
    user: ${LOCAL_USER}
    networks:
      - symfony

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './server/public/:/usr/src/server'
      - './client/public/:/usr/src/client'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php
    networks:
      - symfony
networks:
  symfony:
